### ISSUE TITLE
Convert back to editor js json block from html

### ISSUE THREAD

**Issue by mbmohib** [pavittarx/editorjs-html#19]
Is there any way to convert HTML to editor js JSON block?

**Comment by pavittarx** [comment]
I do not think it will be possible or feasible for the `editorjs` team as well. 

1. Because, how you translate your editorjs data is upto you. So, you have may have different variations for the same block. Hence, transforming back will not be feasible, provided that you may try passing arbitrary html data into the parser. 
2. Your editorjs data must be treated as the single source of truth. This approach would allow you to load your data into editorjs and edit it to your requirements. 

However, If there is something else or if you think the other way around. I would be very much keen to listen. 
Thank You.
